name: Static analysis placeholder

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "Static analysis placeholder - no checks configured yet"
